app:
  eos:
    name: mainnet
    base: /opt/eos/data/mainnet

eos:
  # https://medium.com/coinmonks/how-to-use-eosjs-api-1-770b037b22ad
  # broadcast: true
  # debug: true
  # sign: false
  # httpEndpoint: 'http://jungle.cryptolions.io:18888'
  httpEndpoint: 'http://127.0.0.1:8888'
  # chainId: '038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca'
  expireInSeconds: 5
